// MCN Alumni Network Data
// Scraped from: https://history.archives.mbl.edu/people-and-courses/course-group/methods-computational-neuroscience
// Cohort years: 1988–2017
// Roles: director, faculty, lecturer, ta, student, assistant

const MCN_DATA = {
  years: [1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017],
  cohorts: {
    1988: {
      directors: ["James M Bower", "Christof Koch"],
      faculty:   ["Paul Adams", "Thomas Albright", "Daniel L Alkon", "Thomas Anastasio", "Richard Andersen", "John G Hildebrand", "John Hopfield", "Stephen Lisberger", "Rudolfo Llina", "Nicos Logothetis", "Eve Marder", "Mark E Nelson", "Alexander Pentland", "V S Ramachandran", "John Rinzel", "Idan Segev", "Terrence Sejnowski", "Roger Traub", "David Van Essen"],
      lecturers: [],
      tas:       [],
      students:  ["Werner Backhous", "Jim Cummings", "Allen Dobbins", "William Frost", "Edward Kairiss", "Alexander Kirillov", "Guy Major", "Yair Manor", "Hiroyoshi Miyakawa", "Barbara Moore", "Laura Reece", "Clay Reid", "John Rose", "Franklin Schuling", "Jeffrey Segall", "William Skaggs", "Brian Smith", "Xiao Jing Wang", "Donald Weir", "Hagit Zabrodsky"],
      assistants:["Upinder Bhalla", "John Uhley", "Matthew Wilson"],
    },
    1989: {
      directors: ["James M Bower", "Christof Koch"],
      faculty:   ["Paul Adams", "Edward Adelson", "Daniel L Alkon", "Richard Andersen", "Clay M Sr Armstrong", "Upinder Bhalla", "Avis H Cohen", "Nancy Kopell", "Rudolfo R Llinas", "Michael Mascagni", "Mark E Nelson", "John Rinzel", "Idan Segev", "Terrence Sejnowski", "John Uhley", "David Van Essen", "Christof Von Der Marlsburg", "Matthew Wilson", "Anthony Zador", "David Zipser"],
      lecturers: [],
      tas:       [],
      students:  ["Ehud Ahissar", "Jeffrey Arle", "Tony Bell", "Sherif Maher Botros", "Bradford Bratton", "Dean Buonomano", "Paul Bush", "John Butman", "Paul Frankel", "Merav Galun", "Jisoon Ihm", "Dieter Jaeger", "Gilles Laurent", "Petra Leuchtenberg", "Patrick Lynn", "Reinould Maex", "Paul Moore", "Valeriy Nenov", "Eduardo Solession", "Ehud Zoharry"],
    },
    1990: {
      directors: ["James M Bower", "Christof Koch"],
      faculty:   ["Paul Adams", "Edward Adelson", "Daniel L Alkon", "Richard Andersen", "David Beeman", "Avis H Cohen", "Norberto Grzywacz", "Nancy Kopell", "Rudolfo R Llinas", "Kevan Martin", "Michael Mascagni", "Kenneth Miller", "Mark E Nelson", "John Rinzel", "David Rumelhart", "Sylvia Ryckebusch", "Terrence Sejnowski", "Allen Selverston", "John Uhley", "Lucia Vaina", "David Van Essen", "Matthew Wilson"],
      lecturers: [],
      tas:       [],
      students:  ["Aric Agmon", "Hagai Agmon", "Dale Anders", "Evyatar Av-Ron", "Eyal Bartfeld", "Ellen Barton", "David Berkowicz", "Neil Berman", "Peter Braam", "Dennis Bray", "Trevor Darrell", "Gyongyi Gaal", "Kurt Haas", "Dirk Kautz", "Markus Lappe", "Sean Marrett", "Douglas Morton", "Dietmar Rapf", "Walter Schneider", "Nelson Spruston", "Christopher Staub", "Fan Gang Zeng"],
    },
    1991: {
      directors: ["James M Bower", "Christof Koch", "Kenneth Miller"],
      faculty:   ["Paul Adams", "Edward Adelson", "Richard Anderson", "Joseph Atick", "David Beeman", "David Berkowicz", "Bill Bialek", "Avis H Cohen", "Erik De Schutter", "Rodney Douglas", "Nancy Kopell", "Rudolfo R Llinas", "David Mackay", "Evelyn Marder", "Michael Mascagni", "Bartlett Mel", "John Rinzel", "Sylvia Ryckebusch", "Terrence Sejnowski", "Michael Speight", "Roger Traub", "John Uhley", "David Van Essen", "Matthew Wilson", "Anthony Zador", "David Zipser"],
      lecturers: [],
      tas:       [],
      students:  ["Jeremy Ahouse", "Loren Alving", "Allison Balogh", "Lawrence Cauller", "Allan Coop", "Virginia De Sa", "Jennifer Grob", "Yoram Gutfreund", "Aurora Isaac", "Daryl R Kipke", "Gwendolen Littlewort", "John Middlebrooks", "Pratik Mukherjee", "Venkatesh Murthy", "Steven Nowlan", "Klaus Obermayer", "Anke Post", "William Rose", "Nava Rubin", "Subbakrishna Shankar", "Diana Smetters", "Jeffrey Utz", "James Winslow"],
    },
    1992: {
      directors: ["James M Bower", "Christof Koch"],
      faculty:   ["Paul Adams", "Richard Anderson", "Joseph Atick", "Bill Bialek", "Avis H Cohen", "Rodney Douglas", "Nancy Kopell", "Rudolfo R Llinas", "Evelyn Marder", "Michael Mascagni", "Kenneth Miller", "John Rinzel", "Idan Segev", "Terrence Sejnowski"],
      lecturers: [],
      tas:       ["David Beeman", "David Berkowicz", "Ojvind Bernander", "Diter Jaeger", "Maurice Lee"],
      students:  ["Erik Cook", "Adelle Coster", "Sharon Crook", "Winrich Freiwald", "Alberto Herrera-Becerra", "Martin Huber", "Michael Irizarry", "Ranu Jung", "Brandt Kehoe", "Ilan Lampl", "Mitchell Maltenfort", "Ferenc Mechler", "Jill Nicolaus", "Harmon Nine", "Monica Paolini", "Yifat Prut", "Iris Reuveni", "Emilio Salinas", "Eyal Seidemann", "Nangavaram Sekar", "Micah Siegel", "Mark Tommerdahl", "Yi Xiong Zhou"],
      assistants:["Maneesh Sahani", "Charles F Stevens", "John Uhley"],
    },
    1993: {
      directors: ["David Kleinfeld", "David Tank"],
      faculty:   ["Joseph Atick", "Mark Bear", "Bill Bialek", "Rodney Douglas", "Bard Ermentrout", "William Frost", "Apostolos Georgopoulos", "Charles Gray", "John Hopfield", "Christof Koch", "Nancy Kopell", "Stephen Kosslyn", "Jeff W Lichtman", "John E Lisman", "David Mccormick", "Bruce Mcnaughton", "Kenneth Miller", "John Rinzel", "David Robinson", "Idan Segev", "H Sebastian Seung", "Karen Sigvardt", "Haim Sompolinsky", "Michael Stryker", "Roger Traub"],
      lecturers: ["David Berkowitz", "David Golomb", "Michael Hines", "Roderick Jensen", "Terrance Kovacs", "Rafael Yuste"],
      tas:       [],
      students:  ["Maria Andreu", "Naama Barkai", "Victoria Booth", "Brian Colder", "Yang Dan", "Chandan Dasgupta", "Didier Depireux", "Patricia Di Lorenzo", "Andrew Hill", "Lindsay Hough", "Michael Hucka", "Robert Jacobs", "Adam Jacobs", "Shan Jiang", "Jurgen Klingauf", "Kevin Martin", "Mayank Mehta", "Partha Mitra", "Chris Passaglia", "Richard D Rabbitt", "Moshe Rapp", "Thorsteinn Rognvaldsson", "Jesper Tegner", "John White"],
    },
    1994: {
      directors: ["David Kleinfeld", "David Tank"],
      faculty:   ["Lawrence Abbott", "Joseph Atick", "Mark Bear", "Bill Bialek", "Ronald L Calabrese", "Carmen Canavier", "Kerry Delaney", "Rodney Douglas", "Bard Ermentrout", "Apostolos Georgopoulos", "Charles Gray", "John Hopfield", "Christof Koch", "Nancy Kopell", "Stephen Kosslyn", "Terry Kovacs", "John E Lisman", "Rodolfo R Llinas", "Kevin Martin", "John Maunsell", "David Mccormick", "Alan Peters", "John Rinzel", "Terrance Sejnowski", "H Sebastian Seung", "Shihab Shamma", "Arthur Sherman", "Boris Shraiman", "Karen Sigvardt", "Frederick Sigworth", "Haim Sompolinsky", "Ben Stowbridge", "Roger Traub", "Michael Vanier", "John White", "Matthew Wilson"],
      lecturers: ["Michael Hines", "Roderick Jensen"],
      tas:       [],
      students:  ["John Anderson", "Joshua Berke", "Dana Cohen", "Gennady Cymbalyuk", "Akira Date", "Christopher Decharms", "Opher Donchin", "Stacia Friedman-Hill", "Christopher P Hickie", "John Kebabian", "Insong Koh", "Jurgen Kupper", "Peter Latham", "Heather Lennox", "Anita Luethi", "Nicholas Poolos", "Ramnarayan Ramachandran", "Lawrence Saul", "Eric Schwartz", "Akaysha Tang", "Toby Velte", "Jun Zhu"],
      assistants:["Joy Langford"],
    },
    1995: {
      directors: ["David Kleinfeld", "David Tank"],
      faculty:   ["Lawrence Abbott", "Joseph Atick", "Robert B Jr Barlow", "Bill Bialek", "James M Bower", "Dennis Bray", "Carol Colby", "Bard Ermentrout", "Stephen Fisher", "Nancy Kopell", "Terry Kovacs", "John E Lisman", "Rodolfo R Llinas", "Robert Malinow", "Kevin Martin", "John Maunsell", "Michael Merzenich", "John Rinzel", "Edmund Rolls", "Terrance Sejnowski", "H Sebastian Seung", "Arthur Sherman", "Karen Sigvardt", "Frederick Sigworth", "Haim Sompolinsky", "Roger Traub", "David Van Essen", "Michael Vanier", "Michael Webster", "John White", "Matthew Wilson", "Rafael Yuste", "Steven Zucker"],
      lecturers: ["Barry Connors", "Leon Cooper", "John Hopfield", "Stephen Kosslyn", "Michael Hines", "Roderick Jensen"],
      tas:       [],
      students:  ["Kurt Ahrens", "Hagai Attias", "Michael Beierlein", "Rani Ben-Yishai", "Roland Bosch", "Emery Brown", "Carson Chow", "Jozsef Csicsvari", "Jeremy Dittman", "John Douglass", "Gaute Einevoll", "Hilary Heuer", "Hemant Kudrimoti", "Daniel Lee", "Zheng Liu", "Srikantan Nagarajan", "David Pinto", "Sridhar Raghavachari", "Elad Schneidman", "Helga Seebauer", "Ross Snider", "Cornelis Van Vreeswijk", "Aviva Weisel Eichler"],
      assistants:["Rob De Ruyter Van Steveninck", "Winifried Denk", "Jennie Halfant"],
    },
    1996: {
      directors: ["David Kleinfeld", "David Tank"],
      faculty:   ["Lawrence Abbott", "Moshe Abeles", "Bill Bialek", "Kerry Delancy", "Alain Destexhe", "Bard Ermentrout", "Kevin Fox", "David Hansel", "Roderick Jensen", "Daniel Johnston", "Nancy Kanwisher", "Nancy Kopell", "Terry Kovacs", "Rodolfo R Llinas", "Kevin Martin", "Partha Mitra", "John Rinzel", "Terrance Sejnowski", "H Sebastian Seung", "Arthur Sherman", "Karen Sigvardt", "Frederick Sigworth", "William Skaggs", "David Somers", "Haim Sompolinsky", "David Sparks", "Karel Svoboda", "Naftali Tishby", "Roger Traub", "Michael Vanier", "Xiao Jing Wang", "Ralf Wessel", "John White", "Steven Zucker"],
      lecturers: ["Allison Doupe", "John Hopfield", "Stephen Kosslyn"],
      tas:       ["Howard Eichenbaum", "David Mccormick", "Robert Shapley"],
      students:  ["Terry Alkasab", "Amir Assadi", "Steve Baccus", "Parveen Bawa", "Janet Casagrand", "Rudi Dekoker", "Valentin Dragoi", "Ulrich Egert", "Jaime Eugenin", "Tom Ferree", "Raj Gandhi", "Andreas Herz", "Anton Krukowski", "Boris Lamotte", "Mickey London", "Anita Rado", "Wouter Jan Rappel", "Aeyal Raz", "Christie Seay", "Krishna Shenoy", "Gregory Smith", "Fred Soo", "Areti Tzelepi"],
      assistants:["Rob De Ruyter Van Steveninck", "Gabby Martinez"],
    },
    1997: {
      directors: ["David Kleinfeld", "David Tank"],
      faculty:   ["Laurence Abbott", "Moshe Abeles", "Richard Andersen", "Robert B Jr Barlow", "William Bialek", "Thomas Collett", "Robert De Ruyter Van Steveninck", "Kerry Delaney", "Bard Ermentrout", "David Hansel", "John Hopfield", "Daniel Johnston", "Nancy Kopell", "Kevin Martin", "Kevan Martin", "David Mccormick", "Wolfram Schultz", "Terrance Sejnowski", "H Sebastian Seung", "Arthur Sherman", "Karen Sigvardt", "Frederick Sigworth", "Haim Sompolinsky", "Mircea Steriade", "David Terman", "Naftali Tishby", "Misha Tsodyks", "Steven Zucker"],
      lecturers: ["Roderick Jensen", "Terrence Kovacs", "John White"],
      tas:       [],
      students:  ["Thomas Adelman", "Yoram Ben Shaul", "Karl Deisseroth", "Reiko Maki Fitzsimonds", "Galit Fuhrmann", "Mark Goldman", "Audrey Guzik", "Richard Hahnloser", "Robert Harris", "Katrina Macleod", "William Miller", "Jonathan Murnick", "Louis Neltner", "Duane Nykamp", "Anitha Pasupathy", "Sharon Peled", "Daniel Reich", "Mark Schnitzer", "Oren Shriki", "Jonathan Simon", "William Vinje", "Martin Wainwright", "James Zackheim"],
      assistants:["Joseph Paton"],
    },
    1998: {
      directors: ["William Bialek", "Robert De Ruyter Van Steveninck"],
      faculty:   ["Laurence Abbott", "Carol Colby", "Thomas Collett", "Kerry Delaney", "Allison Doupe", "Bard Ermentrout", "John Hopfield", "Daniel Johnston", "Darcy Kelley", "David Kleinfeld", "Nancy Kopell", "Eve Marder", "Markus Meister", "Partha Mitra", "Fred Rieke", "H Sebastian Seung", "Karen Sigvardt", "Haim Sompolinsky", "Lubert Stryer", "David Tank", "Naftali Tishby", "Steven Zucker"],
      lecturers: ["Denis Baylor", "Simon Barry Laughlin", "Nikos Logothetis"],
      tas:       ["B Aguera Y Areas", "Roderick Jensen", "Roland Koberle", "Lowell Mclinskey", "Moaz Shamir", "John White"],
      students:  ["Rony Azouz", "Riccardo Barbieri", "Francesco Battaglia", "Guo Qiang Bi", "Naama Brenner", "Daniel Butts", "Thomas Euler", "Adrienne Fairhall", "Jordan Feidler", "Matthew Fellows", "Jed Hartings", "Mathew Jones", "Adam Kepecs", "Ann Lee", "Christian Machens", "Anna Majewska", "Thomas Oertner", "Dmitry Rinberg", "Stephanie Ruggiano", "Mark Van Rossum", "Brian Wright", "Ying Zhang"],
    },
    1999: {
      directors: ["William Bialek", "Rob De Ruyter Van Steveninck"],
      faculty:   ["Laurence Abbott", "Carol Colby", "Yang Dan", "Kerry Delaney", "Allison Doupe", "Bard Ermentrout", "John Hopfield", "Daniel Johnston", "Darcy Kelley", "David Kleinfeld", "Nancy Kopell", "Eve Marder", "Markus Meister", "Kenneth Miller", "Partha Mitra", "Fred Rieke", "H Sebastian Seung", "Karen Sigvardt", "Sara Solla", "Haim Sompolinsky", "David Tank", "Naftali Tishby", "Steven Zucker"],
      lecturers: ["Denis Baylor", "Simon Barry Laughlin", "Nikos Logothetis", "Mandyam V Srinivasan"],
      tas:       ["B Aguera Y Areas", "Roderick Jensen", "Roland Koberle", "Geoffrey David Lewen", "L Nemenman", "John White"],
      students:  ["Alla Borisyuk", "Robert Buss", "Jianhua Cang", "Gal Chechik", "Stephen Cowen", "Sophie Dumont", "Gonzalo Garcia De Polavieja", "Gilad Jacobson", "Jan Karbowski", "Vladimir Kefalov", "James Kozloski", "Carlo Laing", "Guy Mayraz", "Mark Mazurek", "David Naylor", "Ras Petersen", "Steven Prescott", "Jonathan Rubin", "Andrew Spence", "Susanne Still", "Gayle Wittenberg", "David Zeddies"],
      assistants:["Krista Stogryn"],
    },
    2000: {
      directors: ["William Bialek", "Rob De Ruyter"],
      faculty:   ["Laurence Abbott", "Carol Colby", "Thomas Collett", "Yang Dan", "Kerry Delaney", "Allison Doupe", "Bard Ermentrout", "David Ferster", "Alan Gelperin", "John Hopfield", "Daniel Johnston", "Darcy Kelley", "David Kleinfeld", "Nancy Kopell", "Eve Marder", "H Markram", "Kenneth Miller", "Partha Mitra", "Ilya Nemenman", "Fred Rieke", "H Sebastian Seung", "Karen Sigvardt", "Sara Solla", "Haim Sompolinsky", "David Tank", "Naftali Tishby", "Misha Tsodyks", "Steven Zucker"],
      lecturers: ["Denis Baylor", "Michael Berry", "Roland Koberle", "Simon Barry Laughlin", "Nikos Logothetis", "Mandyam V Srinivasan", "Roderick Jensen"],
      tas:       ["B Aguera Y Arcas", "Geoffrey David Lewen", "John White"],
      students:  ["Ranit Aharonov-Barki", "Edward Bartlett", "Clara Bodelon", "Ofer Feinerman", "Gidon Felsen", "Amir Globerson", "Robert Gutig", "Dezhe Jin", "Kukjin Kang", "B Suresh Krishna", "Thomas Lauritzen", "Hemai Parthasarathy", "Ron Paz", "Christian Petereit", "John Pierce", "Uri Rockni", "Susanne Schreiber", "Songhai Shi", "Anton Sirota", "Krisztina Szalisznyo", "Dawn Taylor", "Nachum Ulanovsky", "Justin Werfel"],
      assistants:["Kate Jensen", "Keith Purpura"],
    },
    2001: {
      directors: ["William Bialek", "Robert De Ruyter"],
      faculty:   ["Laurence Abbott", "Kerry Delaney", "Bard Ermentrout", "Alan Gelperin", "John Hopfield", "Daniel Johnston", "Darcy Kelley", "Eve Marder", "Ilya Nemenman", "Fred Rieke", "H Sebastian Seung", "Sara Solla", "Haim Sompolinsky", "David Tank", "Naftali Tishby", "Steven Zucker"],
      lecturers: ["Roland Koberle", "Nikos Logothetis", "Mandyam V Srinivasan", "Roderick Jensen"],
      tas:       ["B Aguera Y Arcas", "Geoffrey David Lewen", "John White"],
      students:  ["Britt Anderson", "Greg Corrado", "Alan Dorval", "Artur Escalada", "Ahmed Faisal", "Nicolas Fourcaud", "Joshua Goldberg", "Jesse Goldberg", "Tim Gollisch", "Michael Gordon", "Thomas Gregor", "Charlotte Grove", "Julie Haas", "Andrea Hasenstaub", "Yonatan Lowenstein", "Maria Neimark", "Remus Osan", "Hysell Oviedo", "Jason Puchalla", "Nicole Rust", "Ana Katrin Schenk", "Tatyana Sharpee", "Arun Sripati", "Armen Stepanyants"],
      assistants:["Kate Jensen"],
    },
    2002: {
      directors: ["William Bialek", "Robert De Ruyter"],
      faculty:   ["Larry Abbott", "Richard Aslin", "Bard Ermentrout", "Adrienne Fairhall", "Alan Gelperin", "Roderick Jensen", "Roland Koberle", "Nancy Kopell", "Geoffrey Lewen", "Pamela Reinagel", "Jenny Saffran", "Elad Schneidman", "Reza Shadmehr", "Sara Solla", "Haim Sompolinsky", "David Tank", "Naftali Tishby", "John White"],
      lecturers: ["Uri Alon", "Blaise Ayuera Y Arcas", "Allison Doupe", "Robert Fettiplace", "John Hopfield", "Dan Johnston", "Mary Kennedy", "Randolf Menzel", "Fred Rieke", "H Sebastian Seung", "Mv Srinivasan", "Steven Zucker"],
      tas:       ["Susanne Still"],
      students:  ["Ernest Barreto", "James Beck", "Santanu Chakraborty", "Eugenia Chiappe", "Michael Connell", "Heather Dobbins", "Michael Farries", "Tara Gaertner", "Marco Herrera-Valdez", "Quentin Huys", "Cheng Chang Lien", "Alex Loebel", "Whee Ky Ma", "Robyn Miller", "Leonid Mirny", "Kimberly Montgomery", "Sazzad Nasir", "Reynaldo Pinto", "Milena Raffi", "Vahid Shahrezaei", "Greg Stephens", "Uri Werner-Reiss", "Geraldine Wright", "Yi Zhou"],
      assistants:["Kate Jensen"],
    },
    2003: {
      directors: ["G Bard Ermentrout", "John White"],
      faculty:   ["Larry Abbott", "Guoqiang Bi", "William Bialek", "Michael Brainard", "Yang Dan", "Michale Fee", "Loren Frank", "Alan Gelperin", "Michael Hasselmo", "Michael Hausser", "Roderick Jensen", "William Kath", "Christof Koch", "Nancy Kopell", "David Pinto", "Jonathan Rubin", "Terrence Sejnowski", "H Sebastian Seung", "Reza Shadmehr", "Jeffrey Smith", "Sara Solla", "Haim Sompolinsky", "David Tank", "David Terman", "Charles Wilson"],
      lecturers: ["Kerry Delaney", "Gabriel Kreiman", "Kamal Sen"],
      tas:       ["Alan Dorval", "Steven Epstein", "Jason Ritt", "Irit Shapira", "Noam Slonim"],
      students:  ["Mark Beenhakker", "Kevin Briggman", "Sen Cheng", "Georgina Cruz", "Christopher Dimattina", "Pranay Goel", "Alexis Hattox", "Alexander Katsov", "Anton Khabbaz", "Cheng Yu Li", "Julien Mayor", "Katherine Nagel", "Rishikesh Narayanan", "Theoden Netoff", "Naama Parush", "Michal Rivlin", "Jonathon Shlens", "Lavi Shpigelman", "Kevin Spitler", "Lung Hao Tai", "Melissa Warden", "Christina Weaver", "Corette Wierenga", "Luk Chong Yeung"],
      assistants:["Jonathan Bettencourt"],
    },
    2004: {
      directors: ["Bard Ermentrout", "John White"],
      faculty:   ["Larry Abbott", "Carson Chow", "Yang Dan", "Rob De Ruyter", "Loren Frank", "Alan Gelperin", "Michael Hausser", "William Kath", "Nancy Kopell", "Steve Kunec", "Nikos Logothetis", "David Pinto", "A David Redish", "John Rinzel", "Elad Schneidman", "Terrence Sejnowski", "Kamal Sen", "H Sebastian Seung", "Jeffrey Smith", "Sara Solla", "Haim Sompolinsky", "Nelson Spruston", "David Terman", "Xiao Jing Wang", "Charles Wilson"],
      lecturers: ["Emre Aksay", "Michael Beierlein", "Michale Fee", "Marla Feller", "David Kleinfeld", "Zachary Mainen"],
      tas:       ["Robert Clewley", "Jonathan Drover"],
      students:  ["Janet Best", "Barak Blumenfeld", "Florin Chirila", "Surya Ganguli", "Jeffrey Gauthier", "Anja Gundlfinger", "Jason Kutch", "Sashi Marella", "Gary Marsat", "Lorin Milescu", "Daniel O'Connor", "Andrew Oster", "Anne Marie Oswald", "Krishnan Padmanabhan", "Ueli Rutishauser", "Srivatsun Sadagopan", "Evelyn Sander", "Sam Sober", "Scott Sternson", "Kelly Suter", "Rachel Trana", "Srinivas Turaga", "Milena Winograd", "Zhongshu Yang"],
      assistants:["Jonathan Bettencourt"],
    },
    2005: {
      directors: ["Bard Ermentrout", "John White"],
      faculty:   ["Larry Abbott", "William Bialek", "Carson Chow", "Yang Dan", "Robert De Ruyter", "Michale Fee", "Loren Frank", "Alan Gelperin", "Mark Goldman", "Boris Gutkin", "Daniel Johnston", "William Kath", "Nancy Kopell", "James Kozloski", "John E Lisman", "Kenneth Miller", "David Pinto", "Alex Reyes", "John Rinzel", "Terrence Sejnowski", "Kamal Sen", "H Sebastian Seung", "Jeffrey Smith", "Sara Solla", "Haim Sompolinsky", "David Terman", "Charles Wilson"],
      lecturers: ["Karen Sigvardt", "Nelson Spruston"],
      tas:       ["Brent Doiron", "Kyle Lillis", "Anne Marie Oswald", "Stephanie Palmer", "Yi Zhou"],
      students:  ["Joshua Bassett", "Joseph Bergan", "Anke Borgmann", "Alexander Chubykin", "Aylin Cimenser", "Yuri Dabaghian", "Francois David", "Fredrik Edin", "Juan Gao", "Henry Greenside", "Yixin Guo", "Farid Hamzei-Sichani", "Robert Haslinger", "Shao Ying Hua", "Ian Joseph", "Abdoul Kane", "Yael Katz", "Hamish Mehaffey", "Ithai Rabinowitch", "Max Schiff", "Roy Smeal", "Gabriel Soto", "Ching Ling Teng", "Ilana Witten"],
      assistants:["Jonathan Bettencourt"],
    },
    2006: {
      directors: ["Bard Ermentrout", "John White"],
      faculty:   ["Larry Abbott", "William Bialek", "James M Bower", "Yang Dan", "Rob De Ruyter", "Loren Frank", "Alan Gelperin", "Robert Guetig", "Boris Gutkin", "Judith Hirsch", "William Kath", "Nancy Kopell", "Simon Barry Laughlin", "Christiane Linster", "Kenneth Miller", "L E Moore", "John Rinzel", "Terrence Sejnowski", "Kamal Sen", "H Sebastian Seung", "Jeffrey Smith", "Sara Solla", "Haim Sompolinsky", "David Tank", "Charles Wilson"],
      lecturers: ["David Ferster", "Michael Hines", "Daniel Johnston", "John E Lisman", "Jerome Mertz", "Karen Sigvardt", "Nelson Spruston"],
      tas:       ["Kyle Lillis", "W William Mehaffey", "Samat Moldakarimov", "Ashlan Reid", "Ilana Witten"],
      students:  ["Omri Barak", "Thomas Berger", "Sebastian Brandt", "Felix Creutzig", "Matthieu Dacher", "Taffeta Elliott", "Fernando Fernandez", "Jonathan Fritz", "Fatma Gurel-Kazanci", "Wendy Huang", "Dongsung Huh", "Janneke Jehee", "Daniel Kimmel", "Amina Kinkhabwala", "Alexay Kozhevnikov", "Mark Kramer", "Mini Kurian", "Jakob Macke", "Matthew Mcginley", "Eran Mukamel", "Asa Muller", "Erin Munro", "Chethan Pandarinath", "Mariel Velez"],
      assistants:["Jonathan Bettencourt"],
    },
    2007: {
      directors: ["Bard Ermentrout", "John White"],
      faculty:   ["Larry Abbott", "Michael Berry", "William Bialek", "James M Bower", "Rob De Ruyter", "Adrienne Fairhall", "Loren Frank", "Alan Gelperin", "Mark Goldman", "Boris Gutkin", "Michael Hines", "Judith Hirsch", "Daniel Johnston", "William Kath", "Nancy Kopell", "Eve Marder", "Jerome Mertz", "Kenneth Miller", "L E Moore", "Terrence Sejnowski", "Kamal Sen", "Karen Sigvardt", "Sara Solla", "Haim Sompolinsky", "Nelson Spruston", "David Terman", "Roger Traub", "Charles Wilson"],
      lecturers: [],
      tas:       ["Corey Acker", "Tilman Kispersky", "Kyle Lillis", "Sashi Marella", "Ashlan Reid"],
      students:  ["Petri Ala-Laurila", "Sari Andoni", "Claire Discenza", "Michael Economo", "Dimitri Fisher", "Christopher Gaiteri", "Julie Goulet", "Paul Hand", "Chris Honey", "Hope Johnson", "Nicola Jung", "Wonryull Koh", "Minjoon Kouh", "Andreas Liu", "Beth Lopour", "Brian Lundstrom", "Patrick Meuth", "Murtaza Mogri", "Naveen Nagarajan", "Michael Pesavento", "Kristen Richardson", "Peiyuan Wang", "Ayse Yarali", "Yanyan Zhang"],
      assistants:["Jonathan Bettencourt"],
    },
    2008: {
      directors: ["Michael Berry", "Adrienne Fairhall"],
      faculty:   ["Larry Abbott", "Rava Azeredo Da Silveira", "Stephen Baccus", "Yang Dan", "Rob De Ruyter", "Bard Ermentrout", "Ila Fiete", "Mark Goldman", "Michael Hausser", "Michael Hines", "Eugene Izhikevich", "Daniel Johnston", "Nancy Kopell", "Simon Barry Laughlin", "Michael Mauk", "Mayank Mehta", "Bence Olveczky", "Jonathan Pillow", "Jennifer Raymond", "Elad Schneidman", "Terrence Sejnowski", "Sara Solla", "Haim Sompolinsky", "Roger Traub", "Xiao Jing Wang", "Charles Wilson"],
      lecturers: ["James Dicarlo", "Bartlett Mel"],
      tas:       ["Brian Lundstrom", "Rebecca Mease", "Kolia Sadeghi", "Sean Slee", "Barry Wark"],
      students:  ["Efrat Barak Shimron", "Andrea Barreiro", "Yoram Burak", "Guifen Chen", "Ann Clemens", "Chris Deister", "Gina Escobar", "James Finley", "Robert Froemke", "Elad Ganmor", "Cong Guo", "Xiaoying Huang", "Phillip Larimer", "Jennifer Li", "Zaneta Navratilova", "Jacob Rinaldi", "Daniel Rojas", "Biswa Sengupta", "Rebecca Shafee", "Shiva Sinha", "Simon Sponberg", "Gasper Tkacik", "Dorea Vierling-Claassen", "Fleur Zeldenrust"],
      assistants:["Lisa Roth"],
    },
    2009: {
      directors: ["Michael Berry", "Adrienne Fairhall"],
      faculty:   ["Ehud Ahissar", "Emre Aksay", "Rava Azeredo Da Silverira", "Andrea Barreiro", "William Bialek", "Gyorgy Buzsaki", "Bard Ermentrout", "Ila Fiete", "Mark Goldman", "Michael Hausser", "Nancy Kopell", "Simon Barry Laughlin", "Eve Marder", "Markus Meister", "Leslie Osborne", "Jonathan Pillow", "Elad Schneidman", "Reza Shadmehr", "Sara Solla", "Haim Sompolinsky", "William Spain", "Karel Svoboda", "Emanuel Todorov", "Charles Wilson"],
      lecturers: ["Larry Abbott", "Dmitri Mitya Chklovskii", "James Dicarlo", "Daniel Johnston", "Harvey Karten", "Roozbeh Kiani", "David Kleinfeld", "Marcelo Magnasco", "Bartlett Mel", "Bence Olveczky", "Michael Shadlen"],
      tas:       ["Alex Loebel", "Rebecca Mease", "Michael Pesavento", "Barry Wark", "Daniel Hill"],
      students:  ["Jose Alcami Ayerbe", "Sindhu Anand", "Emily Caporello", "Maurizio De Pitta", "Belen De Sancristobal", "Hubert Eichner", "Sami El Boustani", "Ahmed El Hady", "Michael Famulare", "James Fitzgerald", "Julijana Gjorgjieva", "Viviana Gradinaru", "Valeriya Gritsenko", "Alla Karpova", "Benjamin Kraus", "Alex Kwan", "Eric Larson", "Victor Luria", "John Murray", "Michael Schwemmer", "Anuttama Sheela Mohan", "Dawn Song", "Nicholas Steinmetz", "Gregory Wayne"],
      assistants:["Emma Karlin"],
    },
    2010: {
      directors: ["Michael Berry Ii", "Adrienne Fairhall"],
      faculty:   ["Rava Azeredo Da Silveira", "Stephen Baccus", "William Bialek", "Bard Ermentrout", "Ila Fiete", "Mark Goldman", "Michael Hausser", "David Kleinfeld", "Nancy Kopell", "Eve Marder", "Mayank Mehta", "Jonathan Pillow", "Elad Schneidman", "H Sebastian Seung", "Reza Shadmehr", "Sara Solla", "Haim Sompolinsky", "Karel Svoboda", "Quan Wen"],
      lecturers: ["Larry Abbott", "Dmitri Mitya Chklovskii", "Winfried Denk", "Michale Fee", "Daniel Johnston", "Roozbeh Kiani", "Robert Legenstein", "Kevan Martin", "Bartlett Mel", "Terrence Sejnowski", "Miles Whittington", "Matthieu Wyart"],
      tas:       ["Michael Famulare", "Julijana Gjorgjieva", "Brian Lundstrom", "Olivier Marre", "Rebecca Mease", "Gasper Tkacik", "Sean Trettel"],
      students:  ["Larissa Albantakis", "Hannah Arnson", "Kris Chaisanguanthum", "Elaine Corbett", "Dani Dumitriu", "Felipe Gerhard", "Sarah Jarvis", "Ashok Kumar", "Guillaume Lajoie", "Chi Hon Lee", "Uri Livneh", "Juan Nunez-Iglesias", "Stephani Otte", "Gustavo Patino", "Elena Phoka", "Jason Prentice", "Thomas Reardon", "Jinsook Roh", "Ran Rubin", "Audrey Sederberg", "S Shushruth", "Daniel Soudry", "Franz Weber", "Dajun Xing"],
      assistants:["Jennelle Liljestrand"],
    },
    2011: {
      directors: ["Michael Berry Ii", "Adrienne Fairhall"],
      faculty:   ["Larry Abbott", "Stephen Baccus", "Curtis Bell", "Hagai Bergman", "Emilio Bizzi", "Bard Ermentrout", "Mark Goldman", "David Kleinfeld", "Nancy Kopell", "Yael Niv", "Jonathan Pillow", "Dmitry Rinberg", "Elad Schneidman", "Eric Shea-Brown", "Sara Solla", "Haim Sompolinsky", "Nelson Spruston", "Bryan Toth"],
      lecturers: ["Emre Aksay", "Bruce Bean", "Michale Fee", "Robert Froemke", "John Krakauer", "David Lewis", "Kevan Martin", "Bartlett Mel", "Wolfram Schultz", "Andrew Schwartz", "Miles Whittington"],
      tas:       ["Hubert Eichner", "Michael Famulare", "Michael Farries", "Julijana Gjorgjieva", "Jakob Macke", "Ran Rubin"],
      students:  ["Gautam Agarwal", "Evan Archer", "Yarden Cohen", "Ian Davison", "Antonia Drinnenberg", "Amanda Foust", "J Michael Gee", "Gal Haspel", "Ching Lung Hsu", "Ann Kennedy", "Alix Lacoste", "Christine Lee", "I Chun Lin", "Sisi Ma", "Leonardo Mesquita", "Fiona Muellner", "Lorenz Pammer", "Cengiz Pehlevan", "Daniel Strouse", "Daisuke Takeshita", "Panagiota Theodoni", "Yossi Yovel", "Jiawei Zhang"],
      assistants:["Catherine Eisenhauer"],
    },
    2012: {
      directors: ["Michael Berry Ii", "Adrienne Fairhall"],
      faculty:   ["Larry Abbott", "Emre Aksay", "Rava Azeredo Da Silveira", "Stephen Baccus", "William Bialek", "Bard Ermentrout", "Michale Fee", "Ila Fiete", "Loren Frank", "Gregory Gage", "Alan Gelperin", "Mark Goldman", "John Huguenard", "Roozbeh Kiani", "Nancy Kopell", "Kenneth Miller", "Jonathan Pillow", "Elad Schneidman", "Reza Shadmehr", "Tatyana Sharpee", "Eric Shea-Brown", "Sara Solla", "Haim Sompolinsky", "David Tank", "Bryan Toth", "John White", "Charles Wilson"],
      lecturers: ["Bruce Bean", "James M Bower", "Rob De Ruyter", "Opher Donchin", "Robert Froemke", "David Lewis", "Kevan Martin", "Wolfram Schultz", "Miles Whittington"],
      tas:       ["Sami El Boustani", "James Fitzgerald", "Julijana Gjorgjieva", "Guillaume Lajoie"],
      students:  ["Johnatan Aljadeff", "Wieland Brendel", "Natasha Cayco Gajic", "Sueyeon Chung", "Aleena Garner", "Shirin Hadizadeh", "Emil Hewage", "Yu Hu", "Lacey Kitch", "Belen Lafon", "Liu Dave Liu", "Emily Mackevicius", "Matteo Mischiati", "Michal Moshkovitz", "Eva Naumann", "Nader Nikbakht Nasrabadi", "Eric Reifenstein", "Jennifer Resnik", "Alon Rubin", "Arpiar Saunders", "Merav Stern", "Vladimir Voevodsky", "Catherine Wacongne", "John Widloski"],
      assistants:["Iulia Neagu"],
    },
    2013: {
      directors: ["Michale Fee", "Mark Goldman"],
      faculty:   ["Larry Abbott", "Bruce Bean", "Adrienne Fairhall", "Kenneth Miller", "Liam Paninski", "H Sebastian Seung", "Sara Solla", "Haim Sompolinsky"],
      lecturers: ["Stephen Baccus", "Jeff Beck", "Curtis Bell", "William Bialek", "Carlos Brody", "Dmitri Mitya Chklovskii", "Peter Dayan", "Karl Deisseroth", "Winfried Denk", "Bard Ermentrout", "Ila Fiete", "Robert Froemke", "Gregory Gage", "Jack Gallant", "Surya Ganguli", "Michael Hausser", "David Kleinfeld", "Nancy Kopell", "John E Lisman", "Eve Marder", "Bartlett Mel", "Sheila Nirenberg", "Yael Niv", "Jonathan Pillow", "Andrew Schwartz", "Terrence Sejnowski", "Michael Shadlen", "Eric Shea-Brown", "David Tank", "Daniel Wolpert"],
      tas:       ["Yonatan Aljadeff", "Thomas Chartrand", "Ashok Kumar", "Emily Mackevicius", "Gregory Wayne"],
      students:  ["Anat Arzi", "Alessandro Barri", "Mor Ben-Tov", "Maryam Bijanzadeh", "Tommy Blanchard", "Flora Bouchacourt", "Angela Bruno", "Marcos Cantu", "Conor Dempsey", "Arseny Finkelstein", "Abhinav Grama", "Ana Hocevar Brezavscek", "Yoav Kfir", "Jonathan Leong", "Sam Lewallen", "Laura Lewis", "Hannah Payne", "Mark Roper", "Natalie Steinemann", "Sachiko Tsuda", "Lena Veit", "Alex Williams", "Edward Zagha"],
      assistants:["Julia Udell"],
    },
    2014: {
      directors: ["Michale Fee", "Mark Goldman"],
      faculty:   ["Stephen Baccus", "William Bialek", "Carlos Brody", "Nathaniel Daw", "G Bard Ermentrout", "Adrienne Fairhall", "Ila Fiete", "Loren Frank", "Gregory Gage", "David Kleinfeld", "Peter Latham", "Tim Lewis", "John E Lisman", "Eve Marder", "Jonathan Pillow", "A. David Redish", "John Rinzel", "Jonathan Rubin", "Nate Sawtell", "Terrence J Sejnowski", "Maurice A Smith", "Sara Solla", "Haim Sompolinsky", "David Tank", "Misha Tsodyks"],
      lecturers: ["Larry Abbott", "Dmitri Mitya Chklovskii", "Jack Gallant", "Surya Ganguli", "Lawrence Jackel", "Margaret S Livingstone", "Bartlett Mel"],
      tas:       ["Johnatan Aljadeff", "Thomas Chartrand", "James Fitzgerald", "Ann Kennedy", "Scott Linderman", "Emily Mackevicius", "Timothy Marzullo", "Srinivas Turaga"],
      students:  ["Alexandra Batchelor", "Jennifer Blackwell", "Braden Brinkman", "Yi-Ju Chen", "Alison Duffy", "Christophe Dupre", "Rainer Engelken", "Gabrielle Gutierrez", "Adrien Jouary", "Andrei Khilkevich", "Karin Knudson", "Chava (Evi) Kopelowitz", "Itamar Landau", "Wu-Jung Lee", "Maxim Manakov", "Lane McIntosh", "Mikhail Proskurin", "Michael Rule", "Etienne Serbe", "Nimrod Shaham", "Manisha Sinha", "Tugce Tasci", "Alison Weber", "Noah Young"],
      assistants:["Kelsey Allen"],
    },
    2015: {
      directors: ["Michale Fee", "Mark Goldman"],
      faculty:   ["Larry Abbott", "Stephen Baccus", "Jeff Beck", "William Bialek", "Peter Dayan", "G Bard Ermentrout", "Adrienne Fairhall", "Ila Fiete", "Michael Frank", "Loren Frank", "Gregory Gage", "Surya Ganguli", "John Huguenard", "David Kleinfeld", "Nancy Kopell", "Eve Marder", "Timothy Marzullo", "Jonathan Pillow", "Ran Rubin", "Michael Shadlen", "Sara Solla", "Haim Sompolinsky", "Srinivas Turaga", "Xiao-jing Wang", "Daniel Wolpert"],
      lecturers: ["Dmitri Mitya Chklovskii", "John E Lisman", "Bartlett Mel", "Maneesh Sahani", "Terrence J Sejnowski", "Joshua Shaevitz"],
      tas:       ["Mikio Aoi", "Adam Charles", "Jacob Davidson", "Yu Hu", "Scott Linderman", "Emily Mackevicius", "Hannah Payne"],
      students:  ["Dyuti Bhattacharya", "Ariel Bowman", "Christina Buetfering", "Diana Burk", "Malcolm D Campbell", "Stéphane Deny", "Gamaleldin Elsayed", "Andrew Fink", "Gily Ginosar", "Kiah Hardcastle", "Roy Harpaz", "Kameron Harris", "Naama Kadmon-Harpaz", "Kamesh Krishnamurthy", "Francisco Luongo", "Francesca Mastrogiuseppe", "Ricardo Merino", "Leenoy Meshulam", "Agostina Palmigiano", "Youngmin Park", "Ruben Portugues", "Vijay Singh", "Evelyn Tang", "Yinan Wan"],
      assistants:["Excel Que"],
    },
    2016: {
      directors: ["Michale Fee", "Mark Goldman"],
      faculty:   ["Larry Abbott", "Stephen Baccus", "Carlos Brody", "Emery Brown", "Dmitri Mitya Chklovskii", "Sophie Deneve", "Uri Eden", "G Bard Ermentrout", "Adrienne Fairhall", "Ila Fiete", "James Fitzgerald", "Loren Frank", "Gregory Gage", "Surya Ganguli", "Maria Geffen", "John Huguenard", "Nancy Kopell", "Daniel Lee", "Eve Marder", "Kenneth Miller", "Terrence J Sejnowski", "Sara Solla", "Haim Sompolinsky", "Michael Stryker", "Daniel Wolpert"],
      lecturers: ["Peter Dayan", "Jack Gallant", "Margaret S Livingstone", "Bartlett Mel", "Eero Simoncelli"],
      tas:       ["Jacob Davidson", "Ahmed El Hady", "Yu Hu", "Emily Mackevicius"],
      students:  ["Kathleen Champion", "Lorenzo Fontolan", "Marina Fridman", "Xinxin Ge", "Olivia Gozel", "Sylvia Guillory", "Reuben Haynes", "David Kastner", "Marcelo Mattar", "Gad Mintz", "Gerald Pho", "Alex Piet", "Karen Schroeder", "Graham Smith", "Jordan Sorokin", "Giulia Spampinato", "Christopher Stock", "Liran Szlak", "Marsa Taheri", "Chung Yiu Jonathan Tang", "Pooja Viswanathan", "Noga Weiss Mosheiff", "Jinyao Yan", "Yilun Zhang"],
      assistants:["Emily Meyer"],
    },
    2017: {
      directors: ["Michale Fee", "Mark S. Goldman"],
      faculty:   ["Stephen A. Baccus", "Josh D. Berke", "Dmitri Mitya Chklovskii", "Uri Eden", "Ila Fiete", "James Fitzgerald", "Stefano Fusi", "Gregory J. Gage", "Surya Ganguli", "Mate Lengyel", "Jonathan W. Pillow", "Sara A. Solla", "Haim Sompolinsky", "Xiao Jing Wang", "Adrienne L. Fairhall"],
      lecturers: ["Larry Abbott", "Carlos Brody", "Emery N. Brown", "Sophie Deneve", "Chris Eliasmith", "G Bard Ermentrout", "Loren M. Frank", "Jack Gallant", "Daniel Johnston", "Nancy J. Kopell", "Eve Marder", "Bartlett W. Mel", "Cristina Savin", "Terrence J Sejnowski"],
      tas:       ["Kiah Hardcastle", "Emily Mackevicius Mackevicius", "Alexander Sood", "Alex H. Williams"],
      students:  ["Singh Amrita", "Bahle Andrew", "Sarel Ayelet", "Schneiders Brita", "Guo Chong", "Raman Dhruva", "Gribkova Ekaterina", "Barello Gregory", "Wei Huayi", "Broek Jantine", "Gill Jonathan", "Quach Kathleen", "Mohan Krithika", "Farrell Matthew", "Emami Melikasadat", "Dhupia Neha", "Namburi Praneeth", "Williams-García Rashid", "Pyle Ryan", "Bidaye Salil", "Harvey Sarah", "Collazos Steven", "Scerra Veronica", "Gadagkar Vikram"],
    },
  },

  // Career info — manually curated from public sources
  // Add yourself: { affiliation: '...', role: '...' }
  careerInfo: {
    "Greg Corrado": { affiliation: "Google DeepMind", role: "Principal Scientist" },
    "Tatyana Sharpee": { affiliation: "Salk Institute", role: "Professor" },
    "Armen Stepanyants": { affiliation: "Northeastern University", role: "Professor" },
    "Andrea Hasenstaub": { affiliation: "UCSF", role: "Professor" },
    "Nicole Rust": { affiliation: "UPenn", role: "Professor" },
    "Tim Gollisch": { affiliation: "University of Göttingen", role: "Professor" },
    "Thomas Gregor": { affiliation: "Princeton / Pasteur", role: "Professor" },
    "Jesse Goldberg": { affiliation: "Cornell University", role: "Professor" },
    "Yoram Burak": { affiliation: "Hebrew University", role: "Professor" },
    "Gasper Tkacik": { affiliation: "IST Austria", role: "Professor" },
    "Simon Sponberg": { affiliation: "Georgia Tech", role: "Professor" },
    "Robert Froemke": { affiliation: "NYU", role: "Professor" },
    "Andrea Barreiro": { affiliation: "SMU", role: "Professor" },
    "Arseny Finkelstein": { affiliation: "Weizmann Institute", role: "Scientist" },
    "Alex Williams": { affiliation: "NYU / Flatiron", role: "Research Scientist" },
    "Laura Lewis": { affiliation: "Boston University", role: "Professor" },
    "Tommy Blanchard": { affiliation: "University of Rochester", role: "Professor" },
    "Hannah Payne": { affiliation: "Columbia University", role: "Research Scientist" },
    "Marcelo Mattar": { affiliation: "NYU", role: "Professor" },
    "Lorenzo Fontolan": { affiliation: "EPFL", role: "Research Scientist" },
    "Pooja Viswanathan": { affiliation: "NYU", role: "Research Scientist" },
    "Noga Weiss Mosheiff": { affiliation: "Hebrew University", role: "Scientist" },
    "Emily Mackevicius": { affiliation: "MIT / Broad Institute", role: "Research Scientist" },
    "Gregory Wayne": { affiliation: "Google DeepMind", role: "Research Scientist" },
    "B Aguera Y Arcas": { affiliation: "Google", role: "Distinguished Scientist" },
    "Surya Ganguli": { affiliation: "Stanford University", role: "Professor" },
    "Jonathan Pillow": { affiliation: "Princeton University", role: "Professor" },
    "Ila Fiete": { affiliation: "MIT", role: "Professor" },
    "Carlos Brody": { affiliation: "Princeton University", role: "Professor" },
    "Adrienne Fairhall": { affiliation: "University of Washington", role: "Professor" },
    "Peter Dayan": { affiliation: "Max Planck Institute", role: "Director" },
    "Michael Berry": { affiliation: "Princeton University", role: "Professor" },
    "Liam Paninski": { affiliation: "Columbia University", role: "Professor" },
    "Kenneth Miller": { affiliation: "Columbia University", role: "Professor" },
    "Eric Shea-Brown": { affiliation: "University of Washington", role: "Professor" },
    "Sara Solla": { affiliation: "Northwestern University", role: "Professor" },
    "Haim Sompolinsky": { affiliation: "Hebrew University / Harvard", role: "Professor" },
    "Larry Abbott": { affiliation: "Columbia University", role: "Professor" },
    "Eve Marder": { affiliation: "Brandeis University", role: "Professor" },
    "William Bialek": { affiliation: "Princeton University", role: "Professor" },
    "Terrence Sejnowski": { affiliation: "Salk Institute", role: "Professor" },
    "Mark Goldman": { affiliation: "UC Davis", role: "Professor" },
    "Michale Fee": { affiliation: "MIT", role: "Professor" },
    "H Sebastian Seung": { affiliation: "Princeton University", role: "Professor" },
    "Bard Ermentrout": { affiliation: "University of Pittsburgh", role: "Professor" },
    "Nancy Kopell": { affiliation: "Boston University", role: "Professor" },
    "David Tank": { affiliation: "Princeton University", role: "Professor" },
    "Yael Niv": { affiliation: "Princeton University", role: "Professor" },
  }
};
