#!/usr/bin/env python3
"""
MCN Research-domain Enricher
============================

Labels each resolved MCN person with their research domain(s) so the graph can
color, filter, and cluster people by field of study.

OpenAlex author records carry a ``topics`` array, each entry pre-classified into
a ``subfield -> field -> domain`` hierarchy and sorted by how many of the
author's works fall under it. We take the top topic's **subfield** as the
person's primary research domain (e.g. "Cognitive Neuroscience", "Artificial
Intelligence", "Cellular and Molecular Neuroscience").

Cost: fetching a single author record by id is FREE on OpenAlex (only search
and filtered-list endpoints cost credits), so enriching everyone costs nothing.

Reads:  resolved_authors.json (produced by enrich_collabs.py)
Writes: domains.js

Usage:
    python3 enrich_domains.py            # all resolved people
    python3 enrich_domains.py --refresh  # ignore cache, re-fetch

Only the Python 3 standard library is required.
"""

import argparse
import json
import os
import sys

# Reuse the HTTP/auth/cache/env plumbing from the co-authorship enricher.
import enrich_collabs as ec

HERE = os.path.dirname(os.path.abspath(__file__))
HOW_MANY_TOPICS = 3  # top-N topics kept per person for the detail panel


def fetch_topics(openalex_id, refresh):
    """Return the OpenAlex ``topics`` list for an author id (free single GET)."""
    url = ec.openalex_url(f"authors/{openalex_id}",
                          {"select": "display_name,topics"})
    data = ec.http_get_json(
        url, cache_key=("openalex_authors", f"{openalex_id}.json"), refresh=refresh)
    if not data:
        return []
    return data.get("topics") or []


def primary_domain_and_topics(topics):
    """(primary subfield, [top topic display names]) from a topics list.

    Topics arrive sorted by ``count`` (descending), so topics[0] is dominant.
    Returns (None, []) when the author has no classified topics.
    """
    if not topics:
        return None, []
    subfield = ((topics[0].get("subfield") or {}).get("display_name")) or None
    names = [t.get("display_name") for t in topics[:HOW_MANY_TOPICS] if t.get("display_name")]
    return subfield, names


def write_domains_js(subfield_counts, by_person, out_path):
    """Emit domains.js — same header/JSON style as enrich_collabs.write_collabs_js."""
    ranked = [{"name": name, "count": count}
              for name, count in sorted(subfield_counts.items(),
                                        key=lambda kv: (-kv[1], kv[0]))]
    payload = {"subfields": ranked, "byPerson": by_person}
    header = (
        "// MCN Alumni Network — research domains\n"
        "// Generated by enrich_domains.py from OpenAlex author topics.\n"
        "// Each person's `domain` is their top topic's subfield; `topics` are\n"
        "// their most-published research areas. Regenerate with:\n"
        "//     python3 enrich_domains.py\n\n"
    )
    body = "const MCN_DOMAINS = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n"
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(header + body)


def main():
    ap = argparse.ArgumentParser(description="Label MCN people with research domains.")
    ap.add_argument("--refresh", action="store_true",
                    help="ignore cached author records and re-fetch")
    args = ap.parse_args()

    ec.load_dotenv()
    ec._AUTH["email"] = os.environ.get("MCN_CONTACT_EMAIL")
    ec._AUTH["api_key"] = os.environ.get("OPENALEX_API_KEY")

    resolved_path = os.path.join(HERE, "resolved_authors.json")
    if not os.path.exists(resolved_path):
        sys.exit("resolved_authors.json not found — run enrich_collabs.py first.")
    with open(resolved_path, "r", encoding="utf-8") as fh:
        resolved = json.load(fh)

    print(f"Fetching topics for {len(resolved)} resolved people "
          f"(single-record GETs are free) ...", file=sys.stderr)

    subfield_counts = {}
    by_person = {}
    no_topics = 0
    for i, (name, info) in enumerate(sorted(resolved.items()), 1):
        oid = info.get("openalex_id")
        if not oid:
            continue
        topics = fetch_topics(oid, args.refresh)
        domain, top_names = primary_domain_and_topics(topics)
        by_person[name] = {"domain": domain, "topics": top_names}
        if domain:
            subfield_counts[domain] = subfield_counts.get(domain, 0) + 1
        else:
            no_topics += 1
        if i % 100 == 0:
            print(f"  [{i}/{len(resolved)}] ...", file=sys.stderr)

    write_domains_js(subfield_counts, by_person, os.path.join(HERE, "domains.js"))

    print(f"\nDone.\n"
          f"  People labeled:   {len(by_person)}\n"
          f"  Distinct domains: {len(subfield_counts)}\n"
          f"  No topic data:    {no_topics}\n"
          f"  Output:           domains.js", file=sys.stderr)
    top = sorted(subfield_counts.items(), key=lambda kv: -kv[1])[:12]
    print("  Top domains: " + ", ".join(f"{n} ({c})" for n, c in top), file=sys.stderr)


if __name__ == "__main__":
    main()
